# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cd683952f4ee18113c302156d5dea7622f9f31e9cc6d37f66ff5544624ede0edeb31e268538e6c3953643b151f701fe389df78472c8d9bb972b0c36294640279

test:
  secret_key_base: 6fdbe1538c9f9c1bde8dbe2a7a9c1a34649ba06d560917c506f58306d08e22cedfc223d73032fb3b534df595eb7b605dc37fb45ce36d0bf4f1e53250c65bca3b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
